describe('HSBC Credit Card Flow:', () => {
  it('passes', () => {
    cy.visit('https://www.hsbc.co.in/')
    cy.contains('[class="header-main-navigation-item"]','Banking').click()
    cy.wait(6000)
    cy.contains(' Credit Cards').click({force: true})
    cy.get('a.doormat-heading-link').should('contain', 'Credit Card');
    cy.contains('[class="A-BTNP-RW-ALL"]','Apply now').should('be.visible')
    cy.get('[class="productModule"]').should('have.length',3)
    cy.get('[id="listing_main_image_3"]').first().should('have.attr','alt','HSBC Visa Cashback Credit Card')
    cy.get('[class="row with-bg"]').should('contain','HSBC Cashback Credit Card')
    cy.get('[class="action-buttons sm-12 md-12 lg-12"]').first().should('contain','Compare cards')
    cy.get('[class="action-buttons sm-12 md-12 lg-12"]').first().should('contain','Find out more')
    cy.get('[class="action-buttons sm-12 md-12 lg-12"]').first().should('contain','Apply now')
    cy.contains('[id="listing_main_button_1"]','Compare cards').click()
    cy.get('[class="close-button"]').should('be.visible')
    cy.get('[id="title-pp_tools_productComparator_4"]').should('contain','Select cards to compare')
    cy.get('[class="tile-selector"]').should('have.length',3)
    cy.get('[class="modal-checkbox"]').eq(0).click()
    cy.get('[class="modal-checkbox"]').eq(1).click()
    cy.get('[class="A-BTNP-RW-ALL"]').click()
    cy.wait(7000)
    cy.get('[class="image-select"]').should('have.length',2)
    cy.get('[class="A-TYPS7R-RW-DEV link-icon clear-icon"]').eq(0).contains('Remove card').should('be.visible')
    cy.get('[class="A-TYPS7R-RW-DEV link-icon clear-icon"]').eq(1).contains('Remove card').should('be.visible')
    cy.get('[class="product-select add-product"]').first().click()
    cy.get('[class="modal-checkbox"]').eq(2).click()
    cy.get('[aria-checked="true"]').should('have.length',3)
    cy.get('[class="A-BTNP-RW-ALL"]').click()
    cy.get('[class="A-TYPS7R-RW-DEV link-icon clear-icon"]').eq(0).click()
    cy.get('[class="image-select"]').should('have.length',2)
    cy.get('[class="product-select add-product"]').first().click()
    cy.get('[class="close-button"]').click()
    cy.get('[id="title-pp_tools_productComparator_4"]').should('not.be.visible')
    
    })
  })